/**
 * Implement the `-deps` and `-makedeps` switches, which output dependencies of modules for build tools.
 *
 * The grammar of the `-deps` output is:
 * ---
 *      ImportDeclaration
 *          ::= BasicImportDeclaration [ " : " ImportBindList ] [ " -> "
 *      ModuleAliasIdentifier ] "\n"
 *
 *      BasicImportDeclaration
 *          ::= ModuleFullyQualifiedName " (" FilePath ") : " Protection|"string"
 *              " [ " static" ] : " ModuleFullyQualifiedName " (" FilePath ")"
 *
 *      FilePath
 *          - any string with '(', ')' and '\' escaped with the '\' character
 * ---
 *
 * Make dependencies as generated by `-makedeps` look like this:
 * ---
 * source/app.d:
 *   source/importa.d \
 *   source/importb.d
 * ---
 *
 * Copyright:   Copyright (C) 1999-2026 by The D Language Foundation, All Rights Reserved
 * License:     $(LINK2 https://www.boost.org/LICENSE_1_0.txt, Boost License 1.0)
 * Source:      $(LINK2 https://github.com/dlang/dmd/blob/master/compiler/src/dmd/deps.d, makedeps.d)
 * Documentation:  https://dlang.org/phobos/dmd_deps.html
 * Coverage:    https://codecov.io/gh/dlang/dmd/src/master/compiler/src/dmd/deps.d
 */
module dmd.deps;

import core.stdc.stdio : printf;
import core.stdc.string : strcmp;
import dmd.common.outbuffer;
import dmd.dimport : Import;
import dmd.dmodule : Module;
import dmd.attrib;
import dmd.dscope;
import dmd.dsymbol;
import dmd.dsymbolsem : importAll, include, load, newScope, addMember, setScope;
import dmd.expressionsem;
import dmd.expression : ArgumentList;
import dmd.cond;
import dmd.func;
import dmd.dtemplate : TemplateInstance, TemplateMixin;
import dmd.astcodegen;
import dmd.globals : Param, Output, global;
import dmd.mtype;
import dmd.visitor;
import dmd.arraytypes;
import dmd.declaration;
import dmd.hdrgen : visibilityToBuffer;
import dmd.id : Id;
import dmd.location : Loc;
import dmd.statement;
import dmd.root.filename;
import dmd.root.string : toDString;
import dmd.utils : escapePath;

/**
 * Output the makefile dependencies for the -makedeps switch
 *
 * Params:
 *   buf = outbuffer to write into
 *   params = dmd params
 *   link = an executable is being generated
 *   lib = a library is being generated
 *   libExt = file extension of libraries for current target
 */
void writeMakeDeps(ref OutBuffer buf, const ref Param params, bool link, bool lib, const(char)[] libExt) pure
{
    // start by resolving and writing the target (which is sometimes resolved during link phase)
    if (link && params.exefile)
    {
        buf.writeEscapedMakePath(&params.exefile[0]);
    }
    else if (lib)
    {
        const(char)[] libname = params.libname ? params.libname : FileName.name(params.objfiles[0].toDString);
        libname = FileName.forceExt(libname, libExt);

        buf.writeEscapedMakePath(&libname[0]);
    }
    else if (params.objname)
    {
        buf.writeEscapedMakePath(&params.objname[0]);
    }
    else if (params.objfiles.length)
    {
        buf.writeEscapedMakePath(params.objfiles[0]);
        foreach (of; params.objfiles[1 .. $])
        {
            buf.writestring(" ");
            buf.writeEscapedMakePath(of);
        }
    }
    else
    {
        assert(false, "cannot resolve makedeps target");
    }

    buf.writestring(":");

    // then output every dependency
    foreach (dep; params.makeDeps.files)
    {
        buf.writestringln(" \\");
        buf.writestring("  ");
        buf.writeEscapedMakePath(dep);
    }
    buf.writenl();
}

/**
 * Add an import expression to module dependencies
 * Params:
 *   moduleDeps = output settings for `-deps`
 *   makeDeps = output settings for `-makedeps`
 *   fileNameZ = 0-termminated string containing the import expression's resolved filename
 *   importString = raw string passed to import exp
 *   imod = module import exp is in
 */
void addImportExpDep(ref Output moduleDeps, ref Output makeDeps, const(char)[] fileNameZ, const(char)[] importString, Module imod)
{
    if (moduleDeps.buffer !is null)
    {
        OutBuffer* ob = moduleDeps.buffer;

        if (!moduleDeps.name)
            ob.writestring("depsFile ");
        ob.writestring(imod.toPrettyChars());
        ob.writestring(" (");
        escapePath(ob, imod.srcfile.toChars());
        ob.writestring(") : ");
        if (moduleDeps.name)
            ob.writestring("string : ");
        ob.write(importString);
        ob.writestring(" (");
        escapePath(ob, fileNameZ.ptr);
        ob.writestring(")");
        ob.writenl();
    }
    if (makeDeps.doOutput)
    {
        makeDeps.files.push(fileNameZ.ptr);
    }
}

/**
 * Add an import statement to module dependencies
 * Params:
 *   moduleDeps = output settings
 *   imp = import to add
 *   imod = module that the import is in
 */
void addImportDep(ref Output moduleDeps, Import imp, Module imod)
{
    // object self-imports itself, so skip that
    // https://issues.dlang.org/show_bug.cgi?id=7547
    // don't list pseudo modules __entrypoint.d, __main.d
    // https://issues.dlang.org/show_bug.cgi?id=11117
    // https://issues.dlang.org/show_bug.cgi?id=11164
    if (moduleDeps.buffer is null || (imp.id == Id.object && imod.ident == Id.object) ||
        strcmp(imod.ident.toChars(), "__main") == 0)
        return;

    OutBuffer* ob = moduleDeps.buffer;
    if (!moduleDeps.name)
        ob.writestring("depsImport ");
    ob.writestring(imod.toPrettyChars());
    ob.writestring(" (");
    escapePath(ob, imod.srcfile.toChars());
    ob.writestring(") : ");
    // use visibility instead of sc.visibility because it couldn't be
    // resolved yet, see the comment above
    visibilityToBuffer(*ob, imp.visibility);
    ob.writeByte(' ');
    if (imp.isstatic)
    {
        ob.writestring("static ");
    }
    ob.writestring(": ");
    foreach (pid; imp.packages)
    {
        ob.printf("%s.", pid.toChars());
    }
    ob.writestring(imp.id.toString());
    ob.writestring(" (");
    if (imp.mod)
        escapePath(ob, imp.mod.srcfile.toChars());
    else
        ob.writestring("???");
    ob.writeByte(')');
    foreach (i, name; imp.names)
    {
        if (i == 0)
            ob.writeByte(':');
        else
            ob.writeByte(',');
        auto _alias = imp.aliases[i];
        if (!_alias)
        {
            ob.printf("%s", name.toChars());
            _alias = name;
        }
        else
            ob.printf("%s=%s", _alias.toChars(), name.toChars());
    }
    if (imp.aliasId)
        ob.printf(" -> %s", imp.aliasId.toChars());
    ob.writenl();
}

/**
 * Takes a path, and make it compatible with GNU Makefile format.
 *
 * GNU make uses a weird quoting scheme for white space.
 * A space or tab preceded by 2N+1 backslashes represents N backslashes followed by space;
 * a space or tab preceded by 2N backslashes represents N backslashes at the end of a file name;
 * and backslashes in other contexts should not be doubled.
 *
 * Params:
 *   buf = Buffer to write the escaped path to
 *   fname = Path to escape
 */
void writeEscapedMakePath(ref OutBuffer buf, const(char)* fname) pure
{
    uint slashes;

    while (*fname)
    {
        switch (*fname)
        {
        case '\\':
            slashes++;
            break;
        case '$':
            buf.writeByte('$');
            goto default;
        case ' ':
        case '\t':
            while (slashes--)
                buf.writeByte('\\');
            goto case;
        case '#':
            buf.writeByte('\\');
            goto default;
        case ':':
            // ':' not escaped on Windows because it can
            // create problems with absolute paths (e.g. C:\Project)
            version (Windows) {}
            else
            {
                buf.writeByte('\\');
            }
            goto default;
        default:
            slashes = 0;
            break;
        }

        buf.writeByte(*fname);
        fname++;
    }
}

///
unittest
{
    version (Windows)
    {
        enum input = `C:\My Project\file#4$.ext`;
        enum expected = `C:\My\ Project\file\#4$$.ext`;
    }
    else
    {
        enum input = `/foo\bar/weird$.:name#\ with spaces.ext`;
        enum expected = `/foo\bar/weird$$.\:name\#\\\ with\ spaces.ext`;
    }

    OutBuffer buf;
    buf.writeEscapedMakePath(input);
    assert(buf[] == expected);
}

// DepsCollectVisitor: lightweight AST walk for -deps-only
// Walks parsed AST collecting imports, evaluating conditionals only where needed.
extern(C++) class DepsCollectVisitor : Visitor
{
    alias visit = typeof(super).visit;

    Scope* sc;

    extern(D) this(Scope* sc)
    {
        this.sc = sc;
    }

    // Catch-alls: skip everything we don't specifically handle
    override void visit(Dsymbol d) {}
    override void visit(ASTCodegen.Parameter p) {}
    override void visit(Statement s) {}
    override void visit(ASTCodegen.Type t) {}
    override void visit(ASTCodegen.Expression e) {}
    override void visit(ASTCodegen.TemplateParameter tp) {}
    override void visit(ASTCodegen.Condition c) {}
    override void visit(ASTCodegen.Initializer i) {}



    // Module: recurse into members using existing scope
    override void visit(Module m)
    {
        if (!m.members) return;
        foreach (s; *m.members)
        {
            if (s) s.accept(this);
        }
    }

    // ScopeDsymbol: recurse into members (catches class, struct, union, template, etc.)
    override void visit(ScopeDsymbol sd)
    {
        if (!sd.members) return;
        if (sd.isTemplateDeclaration())
            return;
        foreach (s; *sd.members)
            s.accept(this);
    }

    // TemplateMixin: walk the template's members directly (by name lookup)
    override void visit(TemplateMixin tm)
    {
        // Walk all modules in Module.amodules to find the template declaration
        if (!tm.tempdecl)
        {
            for (size_t i = 0; i < Module.amodules.length; i++)
            {
                auto m = Module.amodules[i];
                if (!m.members) continue;
                foreach (s; *m.members)
                {
                    if (auto td = s.isTemplateDeclaration())
                    {
                        if (td.ident == tm.name)
                        {
                            tm.tempdecl = td;
                            goto Lfound;
                        }
                    }
                }
            }
            Lfound: {}
        }
        if (auto td = tm.tempdecl ? tm.tempdecl.isTemplateDeclaration() : null)
        {
            if (td.members)
            {
                auto savedSc = sc;
                if (td._scope) sc = td._scope;
                foreach (s; *td.members)
                    if (s) s.accept(this);
                sc = savedSc;
            }
        }
    }

    // FuncDeclaration: walk function body (catches ctor, dtor, unittest, etc.)
    // Skip uninstantiated template function bodies to match -deps behavior.
    override void visit(FuncDeclaration fd)
    {
        if (!fd.fbody) return;
        auto p = fd.toParent();
        if ((p && p.isTemplateDeclaration()) ||
            (fd.overnext && fd.overnext.isTemplateDeclaration()))
            return;
        fd.fbody.accept(this);
    }

    // AliasDeclaration: walk aliassym/type (catches template instances via aliases)
    override void visit(AliasDeclaration ad)
    {
        TemplateInstance ti;
        if (ad.aliassym)
            ti = ad.aliassym.isTemplateInstance();
        if (!ti && ad.type)
        {
            if (auto ti2 = ad.type.isTypeInstance())
                ti = ti2.tempinst;
        }
        if (ti)
        {
            // Resolve tempdecl by name
            if (!ti.tempdecl && sc && sc._module && sc._module.members)
            {
                foreach (s; *sc._module.members)
                {
                    if (auto td = s.isTemplateDeclaration())
                    {
                        if (td.ident == ti.name)
                        {
                            ti.tempdecl = td;
                            break;
                        }
                    }
                }
            }
            if (auto td = ti.tempdecl ? ti.tempdecl.isTemplateDeclaration() : null)
            {
                if (td.members)
                {
                    auto savedSc = sc;
                    if (td._scope) sc = td._scope;
                    foreach (s; *td.members)
                        if (s) s.accept(this);
                    sc = savedSc;
                }
            }
            return;
        }
        if (ad.aliassym)
            ad.aliassym.accept(this);
    }

    // UnitTestDeclaration handling
    override void visit(UnitTestDeclaration utd)
    {
        if (utd.fbody)
            utd.fbody.accept(this);
    }

    // Import: register the dependency
    override void visit(Import imp)
    {
        if (imp.semanticRun > PASS.initial) return;
        imp.semanticRun = PASS.semantic;
        if (!imp.mod)
        {
            if (imp.load(sc))
            {
                for (size_t i; i < imp.aliasdecls.length; i++)
                    imp.aliasdecls[i].type = Type.terror;
                imp.semanticRun = PASS.semanticdone;
                addImportDep(global.params.moduleDeps, imp, sc._module);
                return;
            }
            if (imp.mod)
            {
                imp.mod.importAll(null);
            }
        }
        imp.semanticRun = PASS.semanticdone;
        addImportDep(global.params.moduleDeps, imp, sc._module);
    }

    // AttribDeclaration: pass through and recurse into decl
    override void visit(AttribDeclaration ad)
    {
        if (ad.errors || !ad.decl) return;
        foreach (s; *ad.decl)
            s.accept(this);
    }

    // ConditionalDeclaration (version/debug): evaluate condition
    override void visit(ConditionalDeclaration cdc)
    {
        if (cdc.errors || !cdc.condition) return;
        Scope* csc = cdc._scope ? cdc._scope : sc;
        auto savedBuf = global.params.moduleDeps.buffer;
        global.params.moduleDeps.buffer = null;
        bool active = dmd.expressionsem.include(cdc.condition, csc) != 0;
        global.params.moduleDeps.buffer = savedBuf;
        Dsymbols* branch = active ? cdc.decl : cdc.elsedecl;
        if (branch)
        {
            Scope* ns = cdc.newScope(csc);
            foreach (s; *branch)
                s.accept(this);
            if (ns != csc)
                ns.pop();
        }
    }

    // StaticIfDeclaration: evaluate condition (may trigger expressionSemantic)
    override void visit(StaticIfDeclaration sif)
    {
        if (sif.errors || sif.onStack) return;
        sif.onStack = true;
        scope(exit) sif.onStack = false;

        if (sc && sif.condition.inc == Include.notComputed && sif.scopesym && sif._scope)
        {
            auto nerrors = global.errors;

            Scope* saved_scope = sc;
            sc = sif._scope;

            auto savedBuf = global.params.moduleDeps.buffer;
            global.params.moduleDeps.buffer = null;
            bool active = dmd.expressionsem.include(sif.condition, sc) != 0;
            global.params.moduleDeps.buffer = savedBuf;
            global.errors = nerrors;
            Dsymbols* branch = active ? sif.decl : sif.elsedecl;

            if (branch && !sif.addisdone)
            {
                foreach (s; *branch)
                {
                    addMember(s, sif._scope, sif.scopesym);
                    setScope(s, sif._scope);
                }
                sif.addisdone = true;
            }

            sc = saved_scope;

            if (branch)
            {
                Scope* ns = sif.newScope(sc);
                foreach (s; *branch)
                    s.accept(this);
                if (ns != sc)
                    ns.pop();
            }
        }
        else
        {
            // Condition can't be evaluated (e.g. template param refs).
            // Walk both branches conservatively.
            void walk(Dsymbols* branch)
            {
                if (branch)
                {
                    Scope* ns = sif.newScope(sc);
                    foreach (s; *branch)
                        s.accept(this);
                    if (ns != sc)
                        ns.pop();
                }
            }
            walk(sif.decl);
            walk(sif.elsedecl);
        }
    }

    // StaticForeachDeclaration: expand and recurse
    override void visit(StaticForeachDeclaration sfd)
    {
        if (sfd.errors || sfd.onStack) return;
        if (!sfd.cached)
        {
            include(sfd, sc);
        }
        if (sfd.cache)
        {
            foreach (s; *sfd.cache)
                s.accept(this);
        }
    }

    // PragmaDeclaration: recurse into decl
    override void visit(PragmaDeclaration pd)
    {
        if (pd.decl)
        {
            foreach (s; *pd.decl)
                s.accept(this);
        }
    }

    // --- Statement visitors for function-body import capture ---

    // ImportStatement: collect imports inside function bodies
    override void visit(ImportStatement s)
    {
        if (s.imports)
        {
            foreach (imp; *s.imports)
                if (imp) imp.accept(this);
        }
    }

    // CompoundStatement: recurse into statement list
    override void visit(CompoundStatement s)
    {
        if (s.statements)
        {
            foreach (st; *s.statements)
                if (st) st.accept(this);
        }
    }

    // ScopeStatement: recurse into guarded statement
    override void visit(ScopeStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    override void visit(IfStatement s)
    {
        if (s.ifbody) s.ifbody.accept(this);
        if (s.elsebody) s.elsebody.accept(this);
    }

    override void visit(WhileStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(DoStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(ForStatement s)
    {
        if (s.init) s.init.accept(this);
        if (s._body) s._body.accept(this);
    }

    override void visit(ForeachStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(ForeachRangeStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(SwitchStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(CaseStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    override void visit(CaseRangeStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    override void visit(DefaultStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    override void visit(WithStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(TryCatchStatement s)
    {
        if (s._body) s._body.accept(this);
        if (s.catches)
        {
            foreach (c; *s.catches)
                if (c.handler) c.handler.accept(this);
        }
    }

    override void visit(TryFinallyStatement s)
    {
        if (s._body) s._body.accept(this);
        if (s.finalbody) s.finalbody.accept(this);
    }

    override void visit(SynchronizedStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(LabelStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    override void visit(PragmaStatement s)
    {
        if (s._body) s._body.accept(this);
    }

    override void visit(ScopeGuardStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }

    // ConditionalStatement (statement-level version/debug): evaluate condition.
    // Suppress errors since template params may be unbound in function bodies.
    override void visit(ConditionalStatement s)
    {
        auto savedBuf = global.params.moduleDeps.buffer;
        global.params.moduleDeps.buffer = null;
        auto savedErrors = global.errors;
        global.errors = 0;
        bool active = dmd.expressionsem.include(s.condition, sc) != 0;
        bool failed = global.errors != 0;
        global.errors = savedErrors;
        global.params.moduleDeps.buffer = savedBuf;
        if (failed)
        {
            if (s.ifbody) s.ifbody.accept(this);
            if (s.elsebody) s.elsebody.accept(this);
        }
        else if (active)
        {
            if (s.ifbody) s.ifbody.accept(this);
        }
        else
        {
            if (s.elsebody) s.elsebody.accept(this);
        }
    }

    override void visit(StaticForeachStatement s)
    {
        if (s.sfe.aggrfe && s.sfe.aggrfe._body)
            s.sfe.aggrfe._body.accept(this);
        if (s.sfe.rangefe && s.sfe.rangefe._body)
            s.sfe.rangefe._body.accept(this);
    }

    override void visit(UnrolledLoopStatement s)
    {
        if (s.statements)
        {
            foreach (st; *s.statements)
                if (st) st.accept(this);
        }
    }

    override void visit(ForwardingStatement s)
    {
        if (s.statement) s.statement.accept(this);
    }
}
